"use client";
import Link from 'next/link';
import { useCallback,useEffect,useState } from 'react';
import { useSession } from '@/lib/auth/client';
import { getSupabase } from '@/lib/supabase/client';
import { Button } from '@/components/ui/button';
import { RatingStars } from '@/components/reviews/rating-stars';
import {ReviewPhotos,useReviewPhotos} from '@/components/reviews/review-photos';
import {deleteOwnReview} from '@/lib/supabase/delete-review';
type Review={id:string;rating:number;text:string;status:string;created_at:string;temples:{name:string;slug:string}|null};
const labels:Record<string,string>={PENDING:'На проверке',APPROVED:'Опубликован',REJECTED:'Отклонён',HIDDEN:'Скрыт',NEEDS_REVIEW:'На проверке'};
export function MyReviews(){
 const {data:session,status}=useSession();const [items,setItems]=useState<Review[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[pending,setPending]=useState(''),[editing,setEditing]=useState('');
 const media=useReviewPhotos(items.map(r=>r.id));
 const load=useCallback(async()=>{if(!session)return;setLoading(true);setError('');try{const {data,error}=await getSupabase().from('reviews').select('id,rating,text,status,created_at,temples(name,slug)').eq('user_id',session.user.id).order('created_at',{ascending:false});if(error)throw error;setItems(data as unknown as Review[]);}catch{setError('Не удалось загрузить отзывы.');}finally{setLoading(false);}},[session]);
 useEffect(()=>{setItems([]);void load();},[load]);
 if(status==='loading')return <p role="status">Проверяем вход…</p>;
 if(!session)return <Link className="text-primary" href="/login/?callbackUrl=/profile/reviews/">Войдите, чтобы увидеть свои отзывы</Link>;
 return <section className="mx-auto max-w-2xl space-y-5"><h1 className="text-3xl font-semibold">Мои отзывы</h1><p className="text-muted-foreground">После редактирования отзыв снова проходит проверку.</p>{loading&&<p role="status">Загружаем…</p>}{error&&<div role="alert">{error} <Button onClick={()=>void load()} variant="outline">Повторить</Button></div>}{!loading&&!error&&!items.length&&<p>Вы ещё не оставляли отзывов.</p>}{items.map(r=><article className="rounded-2xl border border-card-border bg-card p-5 space-y-3" key={r.id}>{r.temples?<Link className="font-semibold text-primary" href={'/temples/'+r.temples.slug+'/'}>{r.temples.name}</Link>:<p>Храм временно не опубликован</p>}<div className="flex justify-between gap-3"><RatingStars value={r.rating}/><span className="text-sm text-muted-foreground">{labels[r.status]??r.status}</span></div>{editing===r.id?<form className="space-y-3" onSubmit={async event=>{event.preventDefault();const form=new FormData(event.currentTarget);setPending(r.id);setError('');try{const {error}=await getSupabase().from('reviews').update({text:String(form.get('text')).trim(),rating:Number(form.get('rating'))}).eq('id',r.id).eq('user_id',session.user.id);if(error)throw error;setEditing('');await load();}catch{setError('Не удалось сохранить изменения.');}finally{setPending('');}}}><label className="grid gap-2">Оценка<select name="rating" defaultValue={r.rating} className="min-h-11 border rounded-xl bg-background px-3">{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label><label className="grid gap-2">Отзыв<textarea name="text" required maxLength={50000} defaultValue={r.text} className="min-h-36 w-full border rounded-xl bg-background p-3"/></label><Button disabled={pending===r.id}>Сохранить</Button><Button type="button" variant="ghost" onClick={()=>setEditing('')}>Отмена</Button></form>:<p className="whitespace-pre-wrap text-sm leading-6">{r.text}</p>}<ReviewPhotos items={media.photos.filter(p=>p.reviewId===r.id)}/><div className="flex flex-wrap gap-2">{['APPROVED','PENDING','REJECTED'].includes(r.status)&&<Button variant="outline" onClick={()=>setEditing(r.id)} disabled={pending===r.id}>Редактировать</Button>}<Button variant="ghost" disabled={pending===r.id} onClick={async()=>{if(!window.confirm('Удалить свой отзыв?'))return;setPending(r.id);setError('');try{await deleteOwnReview(r.id,session.user.id);setItems(rows=>rows.filter(item=>item.id!==r.id));}catch{setError('Не удалось удалить отзыв.');}finally{setPending('');}}}>Удалить</Button></div></article>)}</section>;
}
