"use client";
import Link from 'next/link';
import {useState} from 'react';
import {useSession} from '@/lib/auth/client';
import {getSupabase} from '@/lib/supabase/client';
import {Button} from '@/components/ui/button';
export function SuggestCorrection({templeId}:{templeId:string}){
 const {data:session}=useSession();const [pending,setPending]=useState(false),[message,setMessage]=useState('');
 return <details className="rounded-2xl border border-card-border bg-card p-5"><summary className="cursor-pointer font-semibold min-h-11">Сообщить об изменении</summary>{!session?<Link className="text-primary" href="/login/">Войдите, чтобы предложить исправление</Link>:<form className="grid gap-3 mt-3" onSubmit={async event=>{event.preventDefault();const node=event.currentTarget,form=new FormData(node);setPending(true);setMessage('');try{const {error}=await getSupabase().from('temple_edit_suggestions').insert({user_id:session.user.id,temple_id:templeId,field_name:form.get('field'),new_value:String(form.get('value')).trim(),source_url:form.get('source')});if(error)throw error;node.reset();setMessage('Исправление отправлено на проверку.');}catch{setMessage('Не удалось отправить исправление. Попробуйте позже.');}finally{setPending(false);}}}><label className="grid gap-2">Что изменилось<select className="rounded-xl border bg-background min-h-11 px-3" name="field"><option value="address">Адрес</option><option value="phone">Телефон</option><option value="email">Почта</option><option value="website_url">Официальный сайт</option><option value="scheduleSummary">Текст расписания</option><option value="sundaySchoolDescription">Воскресная школа</option></select></label><label className="grid gap-2">Актуальные сведения<textarea required name="value" maxLength={10000} className="rounded-xl border bg-background p-3 min-h-24"/></label><label className="grid gap-2">Ссылка на официальный источник<input required type="url" name="source" className="rounded-xl border bg-background min-h-11 px-3"/></label><Button disabled={pending}>{pending?'Отправляем…':'Предложить исправление'}</Button></form>}{message&&<p role="status" className="mt-3 text-sm">{message}</p>}</details>;
}
